# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 11:56
from __future__ import unicode_literals

from django.db import migrations


def create_users(apps, schema_editor):
    # We have to use an import statement rather than apps.get_model, there is a bug in django where users
    # cannot be created using apps.get_model in migrations: https://code.djangoproject.com/ticket/26445
    from django.contrib.auth.models import User, Group

    mod_user_1 = User.objects.create_user(username='moderator_1234', password='password_moderator_1234')
    mod_user_1.save()

    mod_user_2 = User.objects.create_user(username='moderator_2345', password='password_moderator_2345')
    mod_user_2.save()

    mod_user_3 = User.objects.create_user(username='moderator_3456', password='password_moderator_3456')
    mod_user_3.save()

    edit_user_1 = User.objects.create_user(username='editor_1234', password='password_editor_1234')
    edit_user_1.save()

    edit_user_2 = User.objects.create_user(username='editor_2345', password='password_editor_2345')
    edit_user_2.save()

    edit_user_3 = User.objects.create_user(username='editor_3456', password='password_editor_3456')
    edit_user_3.save()

    moderators_group = Group.objects.get(name="Moderators")
    moderators_group.user_set.add(mod_user_1)
    moderators_group.user_set.add(mod_user_2)
    moderators_group.user_set.add(mod_user_3)

    editors_group = Group.objects.get(name="Editors")
    editors_group.user_set.add(edit_user_1)
    editors_group.user_set.add(edit_user_2)
    editors_group.user_set.add(edit_user_3)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_create_initial_user'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
